### ISSUE TITLE
Module parse failed: Unexpected token (120:10)

### ISSUE THREAD

**Issue by svenvg93** [dmartinjs/pitlane#8]
After installing NPM and running `npm install` & `npm start` Im getting the following error. 

```
./src/pages/Results.tsx 120:10
Module parse failed: Unexpected token (120:10)
You may need an appropriate loader to handle this file type.
|       columnNumber: 11
|     }
>   }, race?.Circuit.Location.country, " ", race?.season)), /*#__PURE__*/React.createElement(IonToolbar, {
|     __self: _this,
|     __source: {

```

How can I fix this error?

**Comment by dmartinjs** [comment]
I made a fresh install and unable to reproduce this bug.

When making quick research, this problem occurred because of the optional chaining `?.` in the early days of its integration in typescript and babeljs, causing webpack error during the build process but should be gone since webpack version up to 4 which is the case here (version 5.70.0).

So as a last resort, the only problem I could think of is the usage of an old nodejs version.
can you try to update you nodejs version and retry the `npm run start` ?

**Comment by svenvg93** [comment]
Updating npm solved the problem!
